// Mock data to use when external API is not available
export const mockProducts = [
  {
    id: 1,
    name_ar: "سماعات لاسلكية",
    name_en: "Wireless Headphones",
    description: "سماعات لاسلكية عالية الجودة مع إلغاء الضوضاء",
    description_en: "High-quality wireless headphones with noise cancellation",
    price: 299.99,
    image_url: "/placeholder.svg?height=400&width=400",
    slug: "wireless-headphones",
    category_id: 1,
    stock: 50,
    is_featured: true,
    colors: ["أسود", "أبيض", "فضي"],
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name_ar: "حافظة هاتف جلدية",
    name_en: "Leather Phone Case",
    description: "حافظة هاتف جلدية فاخرة",
    description_en: "Premium leather phone case",
    price: 49.99,
    image_url: "/placeholder.svg?height=400&width=400",
    slug: "leather-phone-case",
    category_id: 2,
    stock: 100,
    is_featured: false,
    colors: ["بني", "أسود"],
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name_ar: "شاحن سريع",
    name_en: "Fast Charger",
    description: "شاحن سريع 65 واط",
    description_en: "65W fast charger",
    price: 79.99,
    image_url: "/placeholder.svg?height=400&width=400",
    slug: "fast-charger",
    category_id: 3,
    stock: 75,
    is_featured: true,
    colors: ["أبيض"],
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    name_ar: "كابل USB-C",
    name_en: "USB-C Cable",
    description: "كابل USB-C متين بطول 2 متر",
    description_en: "Durable 2m USB-C cable",
    price: 19.99,
    image_url: "/placeholder.svg?height=400&width=400",
    slug: "usb-c-cable",
    category_id: 3,
    stock: 200,
    is_featured: false,
    colors: ["أسود", "أبيض"],
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    name_ar: "حامل هاتف للسيارة",
    name_en: "Car Phone Holder",
    description: "حامل هاتف مغناطيسي للسيارة",
    description_en: "Magnetic car phone holder",
    price: 29.99,
    image_url: "/placeholder.svg?height=400&width=400",
    slug: "car-phone-holder",
    category_id: 4,
    stock: 150,
    is_featured: false,
    colors: ["أسود"],
    created_at: new Date().toISOString(),
  },
  {
    id: 6,
    name_ar: "ساعة ذكية",
    name_en: "Smart Watch",
    description: "ساعة ذكية مع مراقبة الصحة",
    description_en: "Smart watch with health monitoring",
    price: 399.99,
    image_url: "/placeholder.svg?height=400&width=400",
    slug: "smart-watch",
    category_id: 5,
    stock: 30,
    is_featured: true,
    colors: ["أسود", "فضي", "ذهبي"],
    created_at: new Date().toISOString(),
  },
]

export const mockCategories = [
  {
    id: 1,
    name_ar: "سماعات",
    name_en: "Headphones",
    description: "سماعات وأجهزة صوتية",
    description_en: "Headphones and audio devices",
    image_url: "/placeholder.svg?height=300&width=300",
    slug: "headphones",
  },
  {
    id: 2,
    name_ar: "حافظات",
    name_en: "Cases",
    description: "حافظات للهواتف والأجهزة",
    description_en: "Cases for phones and devices",
    image_url: "/placeholder.svg?height=300&width=300",
    slug: "cases",
  },
  {
    id: 3,
    name_ar: "شواحن وكوابل",
    name_en: "Chargers & Cables",
    description: "شواحن وكوابل متنوعة",
    description_en: "Various chargers and cables",
    image_url: "/placeholder.svg?height=300&width=300",
    slug: "chargers-cables",
  },
  {
    id: 4,
    name_ar: "حوامل",
    name_en: "Holders",
    description: "حوامل للهواتف والأجهزة",
    description_en: "Holders for phones and devices",
    image_url: "/placeholder.svg?height=300&width=300",
    slug: "holders",
  },
  {
    id: 5,
    name_ar: "ساعات ذكية",
    name_en: "Smart Watches",
    description: "ساعات ذكية ومتتبعات",
    description_en: "Smart watches and trackers",
    image_url: "/placeholder.svg?height=300&width=300",
    slug: "smart-watches",
  },
]
